version: '3.0'
services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
  dev:
    build: ./dev
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      KEYSTORE_PASSWORD: "12345678"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "CAROOT=/workspace/docker/cert mkcert -install; while sleep 1000; do :; done"

volumes:
  db_data: {}
