version: '3.0'
services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
  dev:
    build: ./dev
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    links:
      - db
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  db_data: {}
